### PR TITLE
Update the plugin with the recent partial metadata changes

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by ekinanp** [comment]
After this I'll need to update the corresponding wash-ruby gem blog post on Wash website, then website changes should be finished.

**Comment by ekinanp** [comment]
Not sure why CI is failing now.

**Comment by MikaelSmith** [comment]
Going to dig into it? Looks like possibly a change to pupperware.

**Comment by ekinanp** [comment]
Ok, this is ready now.

**Review by MikaelSmith — APPROVED** [review]

**Pull request merged**
